version: 0.2

env:
  variables:
    REPOSITORY_URI: "218014315265.dkr.ecr.us-east-1.amazonaws.com/my-ecr-repo"
    IMAGE_TAG: "latest"

phases:
  pre_build:
    commands:
      - echo "Ensuring jq is installed..."
      - if ! command -v jq &> /dev/null; then apk add --no-cache jq; fi
      - echo "Retrieving credentials..."
      - SECRET_JSON=$(aws secretsmanager get-secret-value --secret-id aws --query SecretString --output text)
      - USERNAME=$(echo $SECRET_JSON | jq -r .username)
      - PASSWORD=$(echo $SECRET_JSON | jq -r .password)
      - echo "Logging into Docker Hub..."
      - echo "$PASSWORD" | docker login -u "$USERNAME" --password-stdin
  build:
    commands:
      - echo "========== BUILD PHASE =========="
      - echo "Building the Docker image from Dockerfile..."
      - docker build -t $REPOSITORY_URI:latest -t $REPOSITORY_URI:$IMAGE_TAG .

  post_build:
    commands:
      - echo "========== POST-BUILD PHASE =========="
      - echo "Pushing the Docker image to ECR..."
      - docker push $REPOSITORY_URI:latest
      - docker push $REPOSITORY_URI:$IMAGE_TAG
      - echo "Connecting to EKS Cluster..."
      - aws eks update-kubeconfig --region us-east-1 --name skillslab-ticketing-cluster-dev 
      - echo "Applying Kubernetes manifests..."
      - kubectl apply -f deployment.yml --v=6 --validate=false|| { echo "kubectl failed! Check logs above for specific error."; exit 1; }
      - echo "Containerized application artifact successfully deployed to EKS!"