version: 0.2

env:
  variables:
    REPOSITORY_URI: "218014315265.dkr.ecr.us-east-1.amazonaws.com/my-ecr-repo"
    IMAGE_TAG: "latest"

phases:
  install:
    commands:
      - echo "Installing jq on build host..."
      - apt-get update && apt-get install -y jq
  pre_build:
    commands:
      - echo "Retrieving credentials..."
      - SECRET_DATA=$(aws secretsmanager get-secret-value --secret-id aws --query SecretString --output text)
      - echo "DEBUG - Secret data received"
      - echo $SECRET_DATA
      - echo "Extracting credentials using jq"
      - USERNAME=$(echo $SECRET_DATA | jq -r .username)
      - PASSWORD=$(echo $SECRET_DATA | jq -r .password)
      - echo "DEBUG - Extracted Username"
      - echo $USERNAME
      - echo "Logging into Docker Hub"
      - echo "$PASSWORD" | docker login -u "$USERNAME" --password-stdin
  build:
    commands:
      - echo "========== BUILD PHASE =========="
      - echo "Building the Docker image from Dockerfile..."
      - docker build -t $REPOSITORY_URI:latest -t $REPOSITORY_URI:$IMAGE_TAG .

  post_build:
    commands:
      - echo "========== POST-BUILD PHASE =========="
      - echo "Pushing the Docker image to ECR..."
      - docker push $REPOSITORY_URI:latest
      - docker push $REPOSITORY_URI:$IMAGE_TAG
      - echo "Connecting to EKS Cluster..."
      - aws eks update-kubeconfig --region us-east-1 --name skillslab-ticketing-cluster-dev 
      - echo "Applying Kubernetes manifests..."
      - kubectl apply -f deployment.yml --v=6 --validate=false|| { echo "kubectl failed! Check logs above for specific error."; exit 1; }
      - echo "Containerized application artifact successfully deployed to EKS!"