apiVersion: apps/v1
kind: Deployment
metadata:
  name: ticketing-app
  namespace: default
  labels:
    app: ticketing-app
spec:
  replicas: 
  selector:
    matchLabels:
      app: ticketing-app
  template:
    metadata:
      labels:
        app: ticketing-app
    spec:
      containers:
      - name: ticketing-app
      
        image: 218014315265.dkr.ecr.us-east-1.amazonaws.com/my-ecr-repo:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: ticketing-app-service
  namespace: default
spec:
  type: LoadBalancer #
  selector:
    app: ticketing-app
  ports:
    - protocol: TCP
      port: 80      
      targetPort: 5000